services:
  java_app:
    container_name: running-tracker
    image: running-tracker:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - DATABASE_USERNAME=username
      - DATABASE_PASSWORD=password

    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15.8
    ports:
      - "5433:5433"
    environment:
        POSTGRES_USER: username
        POSTGRES_PASSWORD: password
        POSTGRES_DB: postgres